FROM python:3.9

RUN apt-get update && apt-get install pylint pip3 -y 

COPY /deployment/requirements.txt /app/deployment/requirements.txt

RUN pip3 install -r deployment/requirements.txt

WORKDIR /app

COPY . .